### ISSUE TITLE
Primary key constraint violation

### ISSUE THREAD

**Issue by brandondong** [alex-w0/objection-js-soft-delete#109]
With a table like the following (many to many mapping between organizations and users) and its primary key being across all three columns:
```sql
CREATE TABLE membership
(
  organization_id integer NOT NULL,
  user_id integer NOT NULL,
  deleted_on bigint NOT NULL DEFAULT 0
)
```
With these soft delete settings:
```javascript
export const ModelWithSoftDelete = objectionSoftDelete({
  columnName: 'deleted_on',
  deletedValue: { toJSON: () => new Date().getTime() },
  notDeletedValue: 0,
})(Model);
```
This will result in a primary key constraint violation when performing these steps:
1. Create a membership mapping org 1 to user 1.
2. Delete it.
```javascript
Membership.query()
    .delete()
    .where({ userId, orgId });
```
3. Create the same membership again.
4. Delete it again.

At the end of step 3, you have two rows in the membership table (one deleted and one not). Step 4 performs a patch, setting both rows to the same deleted_on value. This can be worked around by adding a .whereNotDeleted() filter to the delete query.

I would expect https://github.com/alex-w0/objection-js-soft-delete/blob/30da77e19c77294b072e96fdee21e89f8a8fb2a6/src/softDelete.js#L17 to already do that for me. I cannot personally think of any cases where you would want to delete already deleted entries. If deletedValue is fixed, then it makes no difference. If it is dynamic like in our case, then you wouldn't want to write over existing values anyways. It's also worth mentioning that the default deletedValue of new Date() does not behave as one might expect and this { toJSON: () => new Date().getTime() } hack is unfortunately required to get the actual current timestamp.

**Comment by alex-w0** [comment]
I think that should not be handled by the plugin, because it was built in such a way that the statements have to be added manually at the query. If I do this differently here it can lead to duplicate where statements or unwanted behaviour.

For the current date you can use the following: knex.fn.now()
