### ISSUE TITLE
Safedelete models getting error TS2589: Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by niteshrawat1995** [alex-w0/objection-js-soft-delete#160]
* `tsc -p .`  gives the error at class declaration and all objection calls where safe delete model are used.
* This error started coming from 6 days 
* Versions - 
```
"ts-node": "^9.1.1",
"objection": "^2.2.12",
"objection-js-soft-delete": "^3.0.1",
```
* Code sample 
```
export class Member extends softDelete(Model) {
```

**Comment by alex-w0** [comment]
The version `3.0.1` is only compatible with objection `3.0.0` and higher, so please upgrade and try again.

**Comment by marianozunino** [comment]
Having the same issue as @niteshrawat1995 
```
src/database/models/base.model.ts:11:14 - error TS2589: Type instantiation is excessively deep and possibly infinite.
```

```
    "objection-js-soft-delete": "3.0.2",
    "objection": "^3.0.1",
    "typescript": "~4.7.3"
```

**Comment by alex-w0** [comment]
@marianozunino Now I just realized that this error comes from the typescript linting and since I don't use typescript in my project, I didn't notice it until now. Probably this file is responsible for this: https://github.com/alex-w0/objection-js-soft-delete/blob/master/index.d.ts

If you have any idea how we can fix the types that would be great.

**Comment by marianozunino** [comment]
As a quick and dirty work arround I did the following:
- implemented the plugin in ts [gist](https://gist.github.com/marianozunino/febfda732fc3d6715613a51e6fd69d50)
- applyed the mixing to my base model
- added the QueryBuilder to my base model as well :(

I know is not the best solution, but at least you still have the typing from all the models that extend from your base model.

```ts
import { DeleteQueryBuilder, SoftDeleteMixin } from './utils/soft-delete-query-builder';

const softDelete = SoftDeleteMixin();
const model = softDelete(Model);

export class BaseModel extends model {
  public QueryBuilderType!: DeleteQueryBuilder<this>;
  public static QueryBuilder = DeleteQueryBuilder;
  ...other stuff
} 
```

**Comment by salmanirshadkhan** [comment]
@marianozunino  Property 'whereNotDeleted' does not exist on type 'DeleteQueryBuilder<Channel, Channel[]>'.ts(2339)

 its give  this  error

**Comment by salmanirshadkhan** [comment]
@marianozunino  thanks issue is fixed now

**Comment by alex-w0** [comment]
I started to migrate the project to typescript, but have still some issues to find out the correct type that should be used. It would be great if you could contribute to this merge request so we can fix this.

https://github.com/alex-w0/objection-js-soft-delete/blob/typescript-migration/src/index.ts

**Comment by ogeday26** [comment]
Hi Alex, I'am trying to solve this problem too. This problem is critical for mine.

**Comment by alex-w0** [comment]
@ogeday26 Yes, unfortunately. The objection documentation is, at least to me, not clear enough about which type should be used, as it doesn't include an example of a plugin in Typescript at all. So I'm guessing at the moment to find the right one.

**Comment by marianozunino** [comment]
@alex-w0 I tried to continue the devlopment that you started on ts, but once you transpile the file and generate the typings you are back into the `TS2589` error. 

here is the generated `d.ts` file:

```ts
import { Model, Page, QueryBuilder } from 'objection';
interface PluginOptions {
    columnName: string;
    deletedValue: Date | boolean | number;
    notDeletedValue: boolean | null;
}
declare type Constructor<T> = new (...args: any[]) => T;
declare class SDQueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
    ArrayQueryBuilderType: SDQueryBuilder<M, M[]>;
    SingleQueryBuilderType: SDQueryBuilder<M, M>;
    MaybeSingleQueryBuilderType: SDQueryBuilder<M, M | undefined>;
    NumberQueryBuilderType: SDQueryBuilder<M, number>;
    PageQueryBuilderType: SDQueryBuilder<M, Page<M>>;
    static options: {
        columnName: string;
        deletedValue: Date;
        notDeletedValue: null;
    };
    delete(): this['NumberQueryBuilderType'];
    hardDelete(): import("objection").NumberQueryBuilder<this>;
    undelete(): import("objection").NumberQueryBuilder<this>;
    whereDeleted(): this;
    whereNotDeleted(): this;
}
declare function softDelete(pluginOptions?: Partial<PluginOptions>): <T extends Constructor<Model>>(Base: T) => {
    new (...args: any[]): {
        QueryBuilderType: SDQueryBuilder<any, any[]>;
        $modelClass: import("objection").ModelClass<any>;
        $relatedQuery<K extends keyof any>(relationName: K, trxOrKnex?: import("objection").TransactionOrKnex | undefined): import("objection").RelatedQueryBuilder<any[K]>;
        $relatedQuery<RM extends Model>(relationName: string, trxOrKnex?: import("objection").TransactionOrKnex | undefined): import("objection").QueryBuilderType<RM>;
        $query(trxOrKnex?: import("objection").TransactionOrKnex | undefined): SDQueryBuilder<any, any>;
        $id(id: any): void;
        $id(): any;
        $fetchGraph(expression: import("objection").RelationExpression<M>, options?: import("objection").FetchGraphOptions | undefined): SDQueryBuilder<any, any>;
        $formatDatabaseJson(json: import("objection").Pojo): import("objection").Pojo;
        $parseDatabaseJson(json: import("objection").Pojo): import("objection").Pojo;
        $formatJson(json: import("objection").Pojo): import("objection").Pojo;
        $parseJson(json: import("objection").Pojo, opt?: import("objection").ModelOptions | undefined): import("objection").Pojo;
        $beforeValidate(jsonSchema: import("objection").JSONSchema, json: import("objection").Pojo, opt: import("objection").ModelOptions): import("objection").JSONSchema;
        $validate(json?: import("objection").Pojo | undefined, opt?: import("objection").ModelOptions | undefined): import("objection").Pojo;
        $afterValidate(json: import("objection").Pojo, opt: import("objection").ModelOptions): void;
        $beforeInsert(queryContext: import("objection").QueryContext): void | Promise<any>;
        $afterInsert(queryContext: import("objection").QueryContext): void | Promise<any>;
        $afterUpdate(opt: import("objection").ModelOptions, queryContext: import("objection").QueryContext): void | Promise<any>;
        $beforeUpdate(opt: import("objection").ModelOptions, queryContext: import("objection").QueryContext): void | Promise<any>;
        $afterGet(queryContext: import("objection").QueryContext): void | Promise<any>;
        $afterFind(queryContext: import("objection").QueryContext): void | Promise<any>;
        $beforeDelete(queryContext: import("objection").QueryContext): void | Promise<any>;
        $afterDelete(queryContext: import("objection").QueryContext): void | Promise<any>;
        $toDatabaseJson(): import("objection").Pojo;
        $toJson(opt?: import("objection").ToJsonOptions | undefined): import("objection").ModelObject<any>;
        toJSON(opt?: import("objection").ToJsonOptions | undefined): import("objection").ModelObject<any>;
        $setJson(json: object, opt?: import("objection").ModelOptions | undefined): any;
        $setDatabaseJson(json: object): any;
        $setRelated<RM_1 extends Model>(relation: String | import("objection").Relation, related: RM_1 | RM_1[] | null | undefined): any;
        $appendRelated<RM_2 extends Model>(relation: String | import("objection").Relation, related: RM_2 | RM_2[] | null | undefined): any;
        $set(obj: import("objection").Pojo): any;
        $omit(keys: string | string[] | {
            [key: string]: boolean;
        }): any;
        $pick(keys: string | string[] | {
            [key: string]: boolean;
        }): any;
        $clone(opt?: import("objection").CloneOptions | undefined): any;
        $traverse(filterConstructor: typeof Model, traverser: import("objection").TraverserFunction): any;
        $traverse(traverser: import("objection").TraverserFunction): any;
        $traverseAsync(filterConstructor: typeof Model, traverser: import("objection").TraverserFunction): Promise<any>;
        $traverseAsync(traverser: import("objection").TraverserFunction): Promise<any>;
        $knex(): import("knex").Knex<any, any[]>;
        $transaction(): import("knex").Knex<any, any[]>;
    };
    QueryBuilder: typeof SDQueryBuilder;
    readonly modifiers: {
        notDeleted(builder: SDQueryBuilder<any>): void;
        deleted(builder: SDQueryBuilder<any>): void;
    };
    readonly isSoftDelete: boolean;
} & T;
export default softDelete;
```

**Comment by alex-w0** [comment]
I think i was able to fix it -> https://github.com/alex-w0/objection-js-soft-delete/blob/typescript-migration/src/index.ts

Please check it out and give me feedback if everything works for you. To do that, just copy the file to your project and change the import statement.

**Comment by marianozunino** [comment]
@alex-w0 in order to make this able to generate types you need to change yout `tsconfig.json`
```json
     "declaration": true /* Generate .d.ts files from TypeScript and JavaScript files in your project. */,
```
Once you do that, you will find the errors once again.
![imagen](https://user-images.githubusercontent.com/6627528/177328253-d527e443-fc30-4e10-8872-296831423f51.png)

And not only that one, ts will complain about you exporting a private name. If you check the recipe that's in objection repository. the QueryBuilder should be outside of the mixin :( 

![imagen](https://user-images.githubusercontent.com/6627528/177328453-1ffe82b4-e330-46d9-9145-f121dd5ac80e.png)

**Comment by alex-w0** [comment]
@marianozunino The declarations are now enabled. I put ` // @ts-ignore` directly in front of the error `Type instantiation is excessiveley deep....` , which is of course not optimal, but at least it works.

So only the error `Return type of exported function....` needs to be fixed. Any idea how I can move the QueryBuilder outside the function and still have access to the plugin options? That would fix the error.

**Comment by joshkay** [comment]
Any updates on this issue?  I can disable the error on the base model declaration, but it still shows everywhere I reference any classes that extend the base model.

**Comment by alex-w0** [comment]
@joshkay Unfortunately not. I wasn't able to fix the error `Return type of exported function has or is using private name 'SDModel'`.
Doesn't anyone have an idea how we can move the QueryBuilder outside of the function and still have access to the plugin options?

**Comment by joshkay** [comment]
I've barely used typescript unfortunately.

Switching 
```
interface SDInstance<T extends typeof Model> {
    QueryBuilderType: SDQueryBuilder<this> & T['prototype'];
}
```
to
```
interface SDInstance<T extends typeof Model> {
    QueryBuilderType: SDQueryBuilder<this>;
}
```
seems to resolve the error.  I'm not sure what other impact it has however.

Any ideas?

**Comment by alex-w0** [comment]
@joshkay Your solution throwed an error on my branch, so I have changed it to any and also created an abstract class of `SDQueryBuilder` to type the queryBuilder instance outside of the plugin.

Can you check out this branch, run `npm run build` and test the compiled files in the dist folder? Doesn`t look too bad in my opinion. Hopefully this is the solution we are looking for.
https://github.com/alex-w0/objection-js-soft-delete/blob/typescript-migration/src/index.ts

**Comment by joshkay** [comment]
Didn't end up working for me, brought up even more errors.  I ended up adding the dependency locally & modified the `index.d.ts` file to 
```
interface SDInstance<T extends typeof Model> {
    QueryBuilderType: SDQueryBuilder<this> & T['prototype'];
}
```

Wish I was able to provide more help, but all the typings are over my head still.  Thanks for the help!

**Comment by alex-w0** [comment]
Ah you're right, the error in the declaration file disappeared but then on every model it will throw the error `Type instantiation is excessively deep and possibly infinite`, so we are on the same point as previously....

It's really sad that there is no official help from Objection.js and they are just declaring this as not possible.

**Comment by andrucz** [comment]
Please try replacing

`QueryBuilderType: SDQueryBuilder<this & T['prototype']>;`

with

`QueryBuilderType: SDQueryBuilder<this>;`

https://github.com/alex-w0/objection-js-soft-delete/blob/786936c58dbdcf4efd3c39aac9357b8195527193/index.d.ts#L17

I'm in a rush right now so I can't open a pull request.

**Comment by guillermodlpa** [comment]
Hello all!

I was recently migrating a codebase with `objection-js-soft-delete` to TypeScript, so I faced this issue. At first, I started using `@ts-ignore` comments, but in the end it was too problematic.

I played with changing values and comparing with the types of `objection`. After a lot of trial and error, I found a way to make it work in my project. This way, the decorated models with `softDelete` have the right typings, combining objection's model with the additions of this library.

To make it work in my project, I created a `types/objection-js-soft-delete.d.ts` file with the following content:

```ts
declare module 'objection-js-soft-delete' {
  import { Model, QueryBuilder } from 'objection';

  class SoftDeleteQueyBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
    ArrayQueryBuilderType: SoftDeleteQueryBuilder<M>;

    NumberQueryBuilderType: SoftDeleteQueryBuilder<M, number>;

    delete(): this['NumberQueryBuilderType'];
    hardDelete(): this['NumberQueryBuilderType'];
    undelete(): this['NumberQueryBuilderType'];
    whereDeleted(): this['ArrayQueryBuilderType'];
    whereNotDeleted(): this['ArrayQueryBuilderType'];
  }

  interface SoftDeleteInstance<T extends typeof Model> {
    QueryBuilderType: SoftDeleteQueryBuilder<this, this[]>;
  }

  interface SoftDeleteStatic<T extends typeof Model> {
    QueryBuilder: typeof SoftDeleteQueryBuilder;
    isSoftDelete: boolean;
    namedFilters(): object;
    new (): SoftDeleteInstance<T> & T['prototype'];
  }

  export default function softDelete<T extends typeof Model>(
    options?: Partial<{
      columnName: string;
      deletedValue: Date | boolean | number;
      notDeletedValue: boolean | null;
    }>,
  ): (model: T) => Omit<T, 'new'> & SoftDeleteStatic<T>;
}
```

The differences are the type of `QueryBuilderType`, already suggested by @joshkay in a previous comment https://github.com/alex-w0/objection-js-soft-delete/issues/160#issuecomment-1238525475, and removing `T['prototype']` from the return type of `softDelete`. I had to rename all the types to avoid collisions with the library types (`SDInstance` -> `SoftDeleteInstance`)

I hope this helps in the effort of fixing types with `objection-js-soft-delete`!

**Comment by alex-w0** [comment]
@guillermodlpa Oh, wow, your solution looks promising. I got an error `Type 'this' does not satisfy the constraint 'Model'.` in this line `QueryBuilderType: SoftDeleteQueryBuilder<this, this[]>;` which I just ignored with a @ts-ignore, but otherwise everything looks good.

**Comment by alex-w0** [comment]
The new package version `3.0.3` is published, please check it out.

**Comment by guillermodlpa** [comment]
Hello there. Apologies for the late reply!

I upgraded to `3.0.3`, and so far so good ✅ Not seeing anymore the error `Type instantiation is excessively deep and possibly infinite.`, and the type of the model returned seems right, and includes extensions like `whereNotDeleted`. I'll continue working with it in the coming weeks and if I notice anything else strange, I'll post here.

Thanks!

**Comment by alex-w0** [comment]
Glad to hear, so we can finally close this issue :)
