### ISSUE TITLE
[TIP]Get(), First() - Select query only get not delete data

### ISSUE THREAD

**Issue by nguyentuannhat** [alex-w0/objection-js-soft-delete#17]
For example: if we have a DB working(haven't soft delete) then the select query is: "ABCModel.query().get()" and we have 100 different queries like that. 

AFTER: we add soft delete for the Model then we must change the query to "ABCModel.query().get().whereNotDeleted()" and change 100 different queries too. 

It not a good solution.
So i think we should add select query default only get "not delete" data. 

softDeleteModel
```
import objectionSoftDelete from 'objection-js-soft-delete';
import BaseModel from './BaseModel';

// Specify the options for this plugin. This are the defaults.
const softDelete = objectionSoftDelete({
  columnName: 'deleted_at',
  deletedValue: new Date(),
  notDeletedValue: null,
});

class SoftDeleteModel extends softDelete(BaseModel) {
  static query(...args) {
    const query = super.query(...args).whereNull('deleted_at');

    // Somehow modify the query.
    return query.runAfter((result) => result);
  }
}

export default SoftDeleteModel;
```

Then we only change model to: 

class UseModel extends SoftDeleteModel {
....
}

and keep all old the query: ABCModel.query().get() but the result only get not deleted data.

hope it helps

**Comment by alex-w0** [comment]
I agree, that would be a better approach. Other soft delete plugins also behave like this.
I'll give it a try, maybe this can be done easily.

Consequently, we can remove the filters/methods whereNotDeleted and whereDeleted and add instead a new method that is called withDeleted. What do you think?
I think it's rather unusual that someone only wants to have the deleted entries. In that case it's still possible to make the query manually.

**Comment by nguyentuannhat** [comment]
> Consequently, we can remove the filters/methods whereNotDeleted and whereDeleted and add instead a new method that is called withDeleted. What do you think?
> I think it's rather unusual that someone only wants to have the deleted entries. In that case it's still possible to make the query manually.

I think it is a good idea, it like with soft delete of Laravel framework(withTrashed, trashed,... )
[https://laravel.com/docs/8.x/eloquent#querying-soft-deleted-models](https://laravel.com/docs/8.x/eloquent#querying-soft-deleted-models
)

 You can refer to the link

**Comment by alex-w0** [comment]
So you prefer to have two methods withTrashed and onlyTrashed like Laravel?

If we can implement this feature, it will be a breaking change, as it is totally different from the current behaviour of the plugin.

**Comment by nguyentuannhat** [comment]
no no, I mean we just need to add a more method is "withDelete" is enough. the link just shares for you to refer.  :D

**Comment by nguyentuannhat** [comment]
```
import objectionSoftDelete from 'objection-js-soft-delete';
import BaseModel from './BaseModel';

// Specify the options for this plugin. This are the defaults.
const deletedNameColumn = 'deleted_at';
const softDelete = objectionSoftDelete({
  columnName: deletedNameColumn,
  deletedValue: new Date(),
  notDeletedValue: null,
});

class SoftDeleteModel extends softDelete(BaseModel) {
  static query(...args) {
    const query = super.query(...args).whereNull(`${this.tableName}.${deletedNameColumn}`);

    // Somehow modify the query.
    return query.runAfter((result) => result);
  }

  static queryDeleted(...args) {
    const query = super.query(...args).whereNotNull(`${this.tableName}.${deletedNameColumn}`);

    // Somehow modify the query.
    return query.runAfter((result) => result);
  }

  static queryWithDeleted(...args) {
    const query = super.query(...args);

    // Somehow modify the query.
    return query.runAfter((result) => result);
  }
}

export default SoftDeleteModel;
```

The example code have 3 method
ex: 
- UseModel.query() : only notdelete data
- UseModel.queryDeleted(): only deleted data
- USeModel.queryWithDeleted(): both deleted and not delete

Hope it helps you Alex

**Comment by alex-w0** [comment]
Thanks for help, I've created now a [new branch ](https://github.com/alex-w0/objection-js-soft-delete/tree/%2317---Select-query-should-return-not-delete-data), so you're welcome to make pull requests if you want to speed up the implementation.

The implementation of the query method was quite easy, but I've encountered another problem. When someone is using the method queryDeleted then the method itself and the method query will be executed which produces the following query:
`select user.* from user where user.deleted_at is null and user.deleted_at is not null`

**Comment by nguyentuannhat** [comment]
Can you share with me your example? I have checked it working normally. 

const seekerProfile = await SeekerProfile.queryDeleted();

to sql: 'select `seeker_profiles`.* from `seeker_profiles` where `seeker_profiles`.`deleted_at` is not null'

my result: 
{
    "code": 200,
    "message": "Success",
    "data": [
        {
            "id": 3,
            "uuid": "69426430-01fb-429e-ac47-502595ba55aa",
            "seekerId": 31,
            "firstName": "Nguyen22",
            "lastName": "Tuan Nhat",
            "roleId": 1,
            "country": "DZ",
            "region": "16",
            "city": 31230,
            "avatarUrl": "https://dev-media-jv.s3.ap-southeast-1.amazonaws.com/seeker/1611906883460-657000879.jpeg",
            "summary": "dsadsada",
            "createdAt": "2021-02-01T04:58:15.000Z",
            "updatedAt": "2021-02-01T05:13:40.000Z",
            "deletedAt": "2021-02-01T05:13:38.000Z"
        }
    ]
}

**Comment by alex-w0** [comment]
You can find the example code [here](https://github.com/alex-w0/objection-js-soft-delete/blob/%2317---Select-query-should-return-not-delete-data/src/softDelete.js).

and the executed query: `await User.query().whereNotDeleted();`

**Comment by alex-w0** [comment]
I've tested it now and the query affects also all subqueries/joins, which should be fine.

```
SELECT user.id              AS id, 
       user.username        AS username, 
       user.active          AS active, 
       user.deleted_date    AS deleted_date, 
       user.deleted_at      AS deleted_at, 
       contact.id           AS contact:id, 
       contact.first_name   AS contact:first_name, 
       contact.last_name    AS contact:last_name, 
       contact.active       AS contact:active, 
       contact.deleted_date AS contact:deleted_date, 
       contact.deleted_at   AS contact:deleted_at 
FROM   user 
       LEFT JOIN user_contact AS contact_join 
              ON contact_join.user_id = user.id 
       LEFT JOIN (SELECT contact.* 
                  FROM   contact 
                  WHERE  contact.deleted_at IS NULL) AS contact 
              ON contact_join.contact_id = contact.id 
WHERE  user.deleted_at IS NULL 
```

So the only problem could be if the query() method is used that returns non deleted rows but at the same time the join statement should return only the deleted records. Should the user pick in that case the method queryWithDeleted, where he can build his own query?

**Comment by alex-w0** [comment]
@nguyentuannhat I'll also remove the default options from the plugin

```
columnName: 'deleted_at',
deletedValue: new Date(),
notDeletedValue: null,
```
Which means that everyone has to define the options on the initialization of the soft delete plugin, so we can prevent undesired behaviour.

**Comment by nguyentuannhat** [comment]
yeap, i know the problem so in my example code i using query(), queryDeleted() and queryWithDeleted() but your plugin can't modify to like that. Your Idea's not a perfect solution but it be fine.

**Comment by nguyentuannhat** [comment]
> @nguyentuannhat I'll also remove the default options from the plugin
> 
> ```
> columnName: 'deleted_at',
> deletedValue: new Date(),
> notDeletedValue: null,
> ```
> 
> Which means that everyone has to define the options on the initialization of the soft delete plugin, so we can prevent undesired behaviour.

I think to keep the "columnName" in case everyone would change it

**Comment by alex-w0** [comment]
> > I've tested it now and the query affects also all subqueries/joins, which should be fine.
> > ```
> > SELECT user.id              AS id, 
> >        user.username        AS username, 
> >        user.active          AS active, 
> >        user.deleted_date    AS deleted_date, 
> >        user.deleted_at      AS deleted_at, 
> >        contact.id           AS contact:id, 
> >        contact.first_name   AS contact:first_name, 
> >        contact.last_name    AS contact:last_name, 
> >        contact.active       AS contact:active, 
> >        contact.deleted_date AS contact:deleted_date, 
> >        contact.deleted_at   AS contact:deleted_at 
> > FROM   user 
> >        LEFT JOIN user_contact AS contact_join 
> >               ON contact_join.user_id = user.id 
> >        LEFT JOIN (SELECT contact.* 
> >                   FROM   contact 
> >                   WHERE  contact.deleted_at IS NULL) AS contact 
> >               ON contact_join.contact_id = contact.id 
> > WHERE  user.deleted_at IS NULL 
> > ```
> > 
> > 
> > So the only problem could be if the query() method is used that returns non deleted rows but at the same time the join statement should return only the deleted records. Should the user pick in that case the method queryWithDeleted, where he can build his own query?
> 
> yeap, i know the problem so in my example code i using query(), queryDeleted() and queryWithDeleted() but your plugin can't
> modify to like that. Your Idea's not a perfect solution but it be fine.

During some tests I came across another problem. Can you try to use the method queryWithDeleted() and withGraphFetched? Then you will notice that the join will still use the query method and so it's not possible anymore to get also the deleted rows from the relationship.

```
User.queryWithDeleted().withGraphJoined(
   'contact'
 )
 
// Prints the following sql
 select
	`user`.`id` as `id`,
	`user`.`username` as `username`,
	`user`.`active` as `active`,
	`user`.`deleted_date` as `deleted_date`,
	`user`.`deleted_at` as `deleted_at`,
	`contact`.`id` as `contact:id`,
	`contact`.`first_name` as `contact:first_name`,
	`contact`.`last_name` as `contact:last_name`,
	`contact`.`active` as `contact:active`,
	`contact`.`deleted_date` as `contact:deleted_date`,
	`contact`.`deleted_at` as `contact:deleted_at`
from
	`user`
left join `user_contact` as `contact_join` on
	`contact_join`.`user_id` = `user`.`id`
left join (
	select
		`contact` .*
	from
		`contact`
	where
		`contact`.`deleted_at` is null) as `contact` on
	`contact_join`.`contact_id` = `contact`.`id`
```

Didn't find a solution yet.

**Comment by alex-w0** [comment]
> I think to keep the "columnName" in case everyone would change it

I find it more confusing when you do one part of the configuration yourself and another part is coming from the plugin. Better to keep all configuration at the same place.
