### ISSUE TITLE
use static get QueryBuilder() { return MyQueryBuilder; } on model but objection-soft-delete not working

### ISSUE THREAD

**Issue by qburst-varunnath** [alex-w0/objection-js-soft-delete#36]
I am using like below to create custom query builder
static get QueryBuilder() {
return MyQueryBuilder;
}

For that model fetching the records throw error that whereNotDeleted is not a function.

**Comment by alex-w0** [comment]
I've investigated the problem and it's not possible to use the plugin as a custom querybuilder.
Below you can see that the plugin isn't exporting the querybuilder instance, but instead a model will be exported.

```
return class extends Model {
  static get QueryBuilder() {
      return SDQueryBuilder;
  }

  static get modifiers() {
      // patch the notDeleted filter into the list of namedFilters
      return Object.assign({}, super.namedFilters, {
          notDeleted: (b) => {
              b.whereNotDeleted();
          },
          deleted: (b) => {
              b.whereDeleted();
          },
      });
  }

  static get isSoftDelete() {
      return true;
  }
};
```

Of course I can also provide an additional named export with only the query builder instance but then you will loose the benefits of the modifiers that the plugin gives you.
Is there a special reason why you aren't extending the model?

**Comment by qburst-varunnath** [comment]
I am using QueryBuilder in my model to add some Subqueries. I have tried a fix by extending QueryBuilder from SoftDelete like below and seems to be working 
`Class MyQueryBuilder extends SoftDelete.QueryBuilder`

**Comment by alex-w0** [comment]
And what if you create a base model that is extending from softDelete, where you can also create your own subqueries? And afterwards the entities are extending from this base model? So you should have the modifiers from the plugin and also your subqueries available.

```
class BaseModel extends softDelete(options)(Model) {
....your subqueries
}

class User extends BaseModel {
...
}
```

**Comment by qburst-varunnath** [comment]
> And what if you create a base model that is extending from softDelete, where you can also create your own subqueries? And afterwards the entities are extending from this base model? So you should have the modifiers from the plugin and also your subqueries available.
> 
> ```
> class BaseModel extends softDelete(options)(Model) {
> ....your subqueries
> }
> 
> class User extends BaseModel {
> ...
> }
> ```
> 
> Otherwise you can't access the modifiers anymore.

Thanks for your quick response. Actually I am using like you explained
Class MyQueryBuilder extends QueryBuider {
 ...my subqueries
}
class BaseModel extends softDelete(options)(Model) {
...
static QueryBuilder = MyQueryBuilder;
}
Inside this ModelClass I am using a custom Query Builder. I believe that is why I am getting the error that whereNotDeleted is not a function.

**Comment by alex-w0** [comment]
Yes thats the reason, with the line `static QueryBuilder = MyQueryBuilder;` you are overriding the queryBuilder instance from the plugin.
